name: multimedia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  syncfusion_flutter_gauges: ^29.1.38
  google_fonts: ^5.0.0  
  fl_chart: ^0.71.0   
  flutter_svg: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
