/// Flutter icons MyFlutterApp
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
/// * Meteocons, Copyright (C) 2012 by Alessio Atzeni
///         Author:    Alessio Atzeni
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://www.alessioatzeni.com
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData access_time = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timer = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData date_range = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData temperature = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData battery_charging_full = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fuel = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
